const state = {
 game: null,
 category: null,
 serviceId: null,
 currency: "USD",
 arcId: "",
 arcIdSkipped: false,
 pendingArcAction: null,
 clearCartConfirmUntil: 0,
 cart: [],
 cartDrawerCompact: false,
 pendingBlueprintSearch: null,
 bpTab: "Gun Blueprints",
 orderPreviewId: "",
 orderRegion: "EU",
 orderPlatform: "PC",
 riotId: "",
 steamId: "",
 lolRiotId: "",
 lolServer: "",
 wowCharacterRealm: "",
 wowCharName: "",
 wowRealm: "",
 editingCartLineId: null,
 blueprintSelections: {
 "Gun Blueprints": new Set(),
 "Backpack Blueprints": new Set(),
 "Quick Use Blueprints": new Set(),
 "Gun Part Blueprints": new Set()
 }
};
